/**
 * Built-in word list for auto-prompts when a player does not submit a prompt
 * before the timer expires and the field is empty.
 *
 * Words are chosen to be fun, drawable, and unambiguous.
 */
const WORDS: readonly string[] = [
  "elephant",
  "birthday party",
  "skydiving",
  "pizza delivery",
  "astronaut",
  "treasure map",
  "snowman",
  "roller coaster",
  "mermaid",
  "volcano",
  "robot",
  "pirate ship",
  "dragon",
  "haunted house",
  "superhero",
  "campfire",
  "unicorn",
  "submarine",
  "tornado",
  "treehouse",
  "fishing",
  "basketball",
  "ice cream truck",
  "surfing",
  "wizard",
  "dinosaur",
  "hot air balloon",
  "cowboy",
  "jungle",
  "rainbow",
  "motorcycle",
  "penguin",
  "castle",
  "fireworks",
  "ninja",
  "helicopter",
  "pancakes",
  "alien",
  "sailboat",
  "giraffe",
  "beach",
  "thunderstorm",
  "magician",
  "octopus",
  "train",
  "sunflower",
  "parachute",
  "snowboarding",
  "waterfall",
  "butterfly",
  "football",
  "lighthouse",
  "scarecrow",
  "mountain climbing",
  "wedding cake",
  "juggling",
  "hammock",
  "cactus",
  "flamingo",
  "bowling",
  "kangaroo",
  "garden",
  "telescope",
  "dentist",
  "spaghetti",
  "trampoline",
  "photographer",
  "bathtub",
  "barbecue",
  "palm tree",
  "race car",
  "scuba diving",
  "lemonade",
  "igloo",
  "detective",
  "sword fight",
  "cruise ship",
  "popcorn",
  "ballerina",
  "catapult",
  "taco",
  "beekeeper",
  "library",
  "sandcastle",
  "bunk bed",
  "traffic jam",
  "polar bear",
  "windmill",
  "karate",
  "hot dog",
  "disco",
  "birdhouse",
  "yoga",
  "taxi",
  "pumpkin",
  "graduation",
  "accordion",
  "snorkeling",
  "ferris wheel",
  "dominoes",
  "waffle",
  "chess",
  "jackhammer",
  "horseback riding",
  "blender",
  "starfish",
  "tightrope walker",
  "snowball fight",
  "french fries",
  "rocking chair",
  "bubble bath",
  "clown",
  "sushi",
  "backpack",
  "mailbox",
  "seahorse",
  "drums",
  "airplane",
  "banana split",
];

/**
 * Pick a random word from the built-in list.
 */
export function getRandomWord(): string {
  const index = Math.floor(Math.random() * WORDS.length);
  return WORDS[index];
}
